sudo: required

services:
  - docker

os:
  - linux

language: go

go: "1.11"

before_install:
  # Install dep
  # Cause of https://github.com/golang/dep/issues/1846
  - mkdir -p $HOME/gopath/bin
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - cp .env.example .env

install:
  - make install

script:
  - travis_retry make test
