FROM palfrey/rustup-watchexec:1.26 as watchexec

FROM golang:1.11

# Download and install the latest release of dep
ADD https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

# Copy the code from the host and compile it
WORKDIR $GOPATH/src/github.com/markelog/pilgrima
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only

COPY --from=watchexec /root/.cargo/bin/watchexec /bin/
COPY . ./
