version: '3'
services:
  db:
    image: postgres:10
    container_name: db-pilgrima
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:5432"
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: test
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./grafana/data:/var/lib/grafana
  app:
    container_name: app-pilgrima
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "make", "watch"]
    environment:
      DATABASE_HOST: db
    volumes:
      - ./:/go/src/github.com/markelog/pilgrima
    depends_on:
      - db
    links:
      - db
    ports:
      - "${PORT}:${PORT}"
