version: '3'
services:
  db:
    image: postgres
    container_name: db-pilgrima
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "8000:5432"
  app:
    container_name: app-pilgrima
    build: 
      context: .
      dockerfile: Dockerfile.development
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    environment:
      DATABASE_HOST: db
    volumes:
      - ./:/go/src/github.com/markelog/pilgrima
    depends_on:
      - db
    links:
      - db
    ports:
      - "${PORT}:${PORT}"
